### ISSUE TITLE
Living Room Card Status

### ISSUE THREAD

**Issue by biggilottecassi** [Anashost/MY-HA-DASH#3]
Hi,

great work!

I have a question, can you explain how you created this part of your Livingroom Card
![IMG_0152](https://github.com/Anashost/MY-HA-DASH/assets/100193699/043f55d5-524e-4fc8-a971-f19514d58512)

**Comment by Anashost** [comment]
Sure,
Create a toggle named `dropdown livingroom` from helpers to use it as a toggle to show and hide the cards (graph cards).

<details>
  <summary>status bar card</summary>

```
type: custom:stack-in-card
mode: vertical
cards:
  - type: custom:mushroom-chips-card
    card_mod:
      style: |
        ha-card {
         --chip-font-size: 0.3em;
         --chip-icon-size: 0.5em;
         --chip-border-width: 0;
         --chip-box-shadow: none;
         --chip-background: none;
         --chip-border: none;
         --chip-spacing: none;
         --chip-font-weight: bold;
            }
    chips:
      - type: template
        entity: input_boolean.dropdown_livingroom
        icon_color: ''
        icon: |-
          {% if is_state('input_boolean.dropdown_livingroom','off') %}
            mdi:chevron-up
          {% else %}
            mdi:chevron-down
          {% endif %}
        use_entity_picture: true
        double_tap_action:
          action: none
        hold_action:
          action: none
        tap_action:
          action: toggle
        content: ''
      - type: template
        entity: sensor.livingroom_temperature
        icon_color: '{{states(''sensor.livingroom_temp_color_no_rgb'')}}'
        icon: mdi:thermometer
        use_entity_picture: true
        double_tap_action:
          action: none
        hold_action:
          action: none
        tap_action:
          action: more-info
        content: |-
          {% if is_state('sensor.livingroom_temperature','unknown') %}
            -
          {% else %}
            {{states('sensor.livingroom_temperature')}}°
          {% endif %}
      - type: template
        icon: mdi:lightbulb-group
        content: |-
          {% if is_state('sensor.livingroom_lights_of_count','0') %}
            
          {% else %}
            {{states('sensor.livingroom_lights_of_count')}}
          {% endif %}
        icon_color: |-
          {% set state = states('sensor.livingroom_lights_of_count')|float %}
          {% if state <= 0 %} grey
          {% else %} amber
          {% endif %}
        double_tap_action:
          action: none
        hold_action:
          action: more-info
        tap_action:
          action: none
        entity: sensor.livingroom_lights_of_count
      - type: template
        entity: switch.plug_4_local
        icon_color: |-
          {% if is_state('switch.plug_4_local','off') %}
            grey
            {% elif is_state('switch.plug_4_local','unavailable') %}
            white
            {% elif is_state('switch.plug_4_local','unknown') %}
            white
          {% else %}
            cyan
          {% endif %}
        icon: mdi:fan
        use_entity_picture: true
        double_tap_action:
          action: none
        hold_action:
          action: more-info
        tap_action:
          action: none
```
</details>
<details>
  <summary>temperature & humidity graph card</summary>

```
type: conditional
conditions:
  - entity: input_boolean.dropdown_livingroom
    state: 'off'
card:
  type: horizontal-stack
  cards:
    - type: custom:mini-graph-card
      entities:
        - sensor.livingroom_temperature
      line_color: orange
      name: Temperature
      icon: mdi:thermometer
      line_width: 5
      font_size: 75
    - type: custom:mini-graph-card
      entities:
        - sensor.livingroom_humidity
      line_color: rgb(51, 173, 255)
      name: Humidity
      icon: mdi:water-percent
      line_width: 5
      font_size: 75

```
</details>

Note that you need to replace entities with your own, like temperature, lights counter, fan plug.

**Comment by biggilottecassi** [comment]
Thanks and this?
![IMG_0152](https://github.com/Anashost/MY-HA-DASH/assets/100193699/584db77c-2b12-4545-97e5-c9606074f01c)

**Comment by Anashost** [comment]
This is the status bar card, look at my answer again.

**Comment by biggilottecassi** [comment]
Sorry. Wrong screenshot
![IMG_0150](https://github.com/Anashost/MY-HA-DASH/assets/100193699/ad487c3f-fa8e-4b70-ba9f-3542a724c53f)

**Comment by Anashost** [comment]
No worries, these are normal mushroom-chips-card you can configure them mostly from the ui.

**Comment by biggilottecassi** [comment]
Ok. The Card for Setting and PTZ
![IMG_0153](https://github.com/Anashost/MY-HA-DASH/assets/100193699/02cb4e58-a628-4857-8b05-2ee16e1981c1)

**Comment by Anashost** [comment]
I can give you the code but the buttons at the left involves scripts that does some of the actions that are related to my own camera brand.

<details>
  <summary>yaml</summary>

```
square: false
type: grid
cards:
  - type: vertical-stack
    cards:
      - type: custom:stack-in-card
        mode: vertical
        keep:
          outer_padding: true
          margin: true
          box_shadow: false
          background: false
        cards:
          - type: custom:mushroom-chips-card
            chips:
              - type: entity
                entity: script.xxx
                tap_action:
                  action: call-service
                  service: script.xxx
                  target: {}
                icon: mdi:door
                content_info: none
              - type: entity
                entity: script.cam_preset_balcony
                tap_action:
                  action: call-service
                  service: script.cam_preset_balcony
                  target: {}
                icon: mdi:window-open-variant
                content_info: none
              - type: entity
                entity: script.cam_preset_privacy
                tap_action:
                  action: call-service
                  service: script.cam_preset_privacy
                  target: {}
                icon: mdi:eye-off
                content_info: none
              - type: entity
                entity: script.cam_preset_privacy
                tap_action:
                  action: call-service
                  service: script.cam_preset_privacy_off
                  target: {}
                icon: mdi:eye
                content_info: none
            alignment: start
          - type: custom:mushroom-chips-card
            chips:
              - type: entity
                entity: script.cam_night_vision_auto
                contenet: none
                name: auto
                tap_action:
                  action: call-service
                  service: script.cam_night_vision_auto
                  target: {}
                icon: mdi:theme-light-dark
                content_info: none
              - type: entity
                entity: script.cam_night_vision_on
                contenet: none
                name: 'on'
                tap_action:
                  action: call-service
                  service: script.cam_night_vision_on
                  target: {}
                icon: mdi:weather-night
                content_info: none
              - type: entity
                entity: script.cam_night_vision_off
                contenet: none
                name: 'off'
                tap_action:
                  action: call-service
                  service: script.cam_night_vision_off
                  target: {}
                icon: mdi:weather-sunny
                content_info: none
          - type: custom:mushroom-chips-card
            card_mod:
              style: |
                ha-card {
                 --chip-font-size: 0.3em;
                 --chip-icon-size: 0.5em;
                 --chip-border-width: 0;
                 --chip-box-shadow: none;
                 --chip-background: none;
                 --chip-border: none;
                 --chip-spacing: none;
                 --chip-font-weight: bold;
                    }
            chips:
              - type: entity
                entity: script.xxx
                tap_action:
                  action: none
                icon: none
                content_info: none
  - type: custom:stack-in-card
    mode: vertical
    keep:
      outer_padding: true
      margin: true
      box_shadow: false
      background: false
    cards:
      - type: custom:mushroom-chips-card
        chips:
          - type: entity
            entity: button.tapo_cam_move_up
            icon: mdi:chevron-up
            content_info: none
            double_tap_action:
              action: none
            hold_action:
              action: none
            tap_action:
              action: toggle
        alignment: center
      - type: custom:mushroom-chips-card
        chips:
          - type: entity
            entity: button.tapo_cam_move_left
            icon: mdi:chevron-left
            content_info: none
            double_tap_action:
              action: none
            hold_action:
              action: none
            tap_action:
              action: toggle
          - type: entity
            entity: input_boolean.on_state
            icon: mdi:circle
            content_info: none
            double_tap_action:
              action: none
            hold_action:
              action: none
            tap_action:
              action: none
          - type: entity
            entity: button.tapo_cam_move_right
            double_tap_action:
              action: none
            hold_action:
              action: none
            tap_action:
              action: toggle
            icon: mdi:chevron-right
            content_info: none
        alignment: center
      - type: custom:mushroom-chips-card
        chips:
          - type: entity
            entity: button.tapo_cam_move_down
            icon: mdi:chevron-down
            double_tap_action:
              action: none
            hold_action:
              action: none
            tap_action:
              action: toggle
            content_info: none
        alignment: center
columns: 2
```
</details>
