### ISSUE TITLE
Subpages

### ISSUE THREAD

**Issue by detlefh68** [Anashost/MY-HA-DASH#6]
Hi,

You made very great work and I like your dashboard

Can You explain how au created subpages which you for example open from your chips on the top of the living room page.
There ist a fan remote pages and I cannot see any navigation on the top menu.

It a very pretty method to open subpages for things like a fan, hvac, ...

**Comment by Anashost** [comment]
Hey, I'm glad you liked it.

So do you mean sub-pages or sub-cards?
As subpages are just other views that are hidden from users, that's why they dont show up in the navigation bar. You can do that from each view settings (visibility).

**Comment by Anashost** [comment]
For sub-cards (dropdown),  I've explained that in this [issue #3](https://github.com/Anashost/MY-HA-DASH/issues/3#issuecomment-1757456216)

**Comment by detlefh68** [comment]
I mean this subpages 

![image](https://github.com/Anashost/MY-HA-DASH/assets/60793377/422f268f-6517-41f7-95fd-d328d426cd73)

The subpage has no page icon. Is this page hidden for the users?

![image](https://github.com/Anashost/MY-HA-DASH/assets/60793377/608c71e4-af3b-4410-920a-7499087760b4)

The sub-pages (dropdown) is made with an helper and conditional card.

**Comment by Anashost** [comment]
> Hey, I'm glad you liked it.
> 
> So do you mean sub-pages or sub-cards? As subpages are just other views that are hidden from users, that's why they dont show up in the navigation bar. You can do that from each view settings (visibility).

As i said here 👆🏻

So you just created a card like a mushroom-chips-card or mushroom-entity-card and set tap action to navigate, and enter view name.

**Comment by detlefh68** [comment]
OK I understand, that's listen good and the page "forest" in the top navigation bar is gone :-)

Are the system monitoring cards also conditional cards and you switch the graph cards with an helper?

![image](https://github.com/Anashost/MY-HA-DASH/assets/60793377/a44f5329-7997-401b-8b86-4d68092a4306)

**Comment by Anashost** [comment]
> Are the system monitoring cards also conditional cards and you switch the graph cards with an helper?

This view is kind complicated it requires:
* as you said a helper `toggle` for every one of those plugs.
* Conditional cards to only show the plug you clicked on.
* and an automation to switch the `toggles` on and off accordingly.

Here's the automation try to understand it, to be able to edit it with your own entities:

```
alias: "Plugs views switching"
description: ""
trigger:
  - platform: state
    entity_id:
      - input_boolean.p1_drop_down_toggle
    from: "off"
    to: "on"
    id: p1
  - platform: state
    entity_id:
      - input_boolean.p2_drop_down_toggle
    from: "off"
    to: "on"
    id: p2
  - platform: state
    entity_id:
      - input_boolean.p3_drop_down_toggle
    from: "off"
    to: "on"
    id: p3
  - platform: state
    entity_id:
      - input_boolean.p4_drop_down_toggle
    from: "off"
    to: "on"
    id: p4
  - platform: state
    entity_id:
      - input_boolean.p5_drop_down_toggle
    from: "off"
    to: "on"
    id: p5
  - platform: state
    entity_id:
      - input_boolean.p6_drop_down_toggle
    from: "off"
    to: "on"
    id: p6
condition: []
action:
  - choose:
      - conditions:
          - condition: trigger
            id: p1
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - input_boolean.p3_drop_down_toggle
                - input_boolean.p2_drop_down_toggle
                - input_boolean.p4_drop_down_toggle
                - input_boolean.p5_drop_down_toggle
                - input_boolean.p6_drop_down_toggle
      - conditions:
          - condition: trigger
            id: p2
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - input_boolean.p1_drop_down_toggle
                - input_boolean.p3_drop_down_toggle
                - input_boolean.p4_drop_down_toggle
                - input_boolean.p5_drop_down_toggle
                - input_boolean.p6_drop_down_toggle
      - conditions:
          - condition: trigger
            id: p3
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - input_boolean.p1_drop_down_toggle
                - input_boolean.p2_drop_down_toggle
                - input_boolean.p4_drop_down_toggle
                - input_boolean.p5_drop_down_toggle
                - input_boolean.p6_drop_down_toggle
      - conditions:
          - condition: trigger
            id: p4
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - input_boolean.p1_drop_down_toggle
                - input_boolean.p2_drop_down_toggle
                - input_boolean.p3_drop_down_toggle
                - input_boolean.p5_drop_down_toggle
                - input_boolean.p6_drop_down_toggle
      - conditions:
          - condition: trigger
            id: p5
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - input_boolean.p1_drop_down_toggle
                - input_boolean.p2_drop_down_toggle
                - input_boolean.p3_drop_down_toggle
                - input_boolean.p4_drop_down_toggle
                - input_boolean.p6_drop_down_toggle
      - conditions:
          - condition: trigger
            id: p6
        sequence:
          - service: input_boolean.turn_off
            data: {}
            target:
              entity_id:
                - input_boolean.p1_drop_down_toggle
                - input_boolean.p2_drop_down_toggle
                - input_boolean.p3_drop_down_toggle
                - input_boolean.p4_drop_down_toggle
                - input_boolean.p5_drop_down_toggle
mode: single

```
